server:
  port: 9090

spring:
  application:
    name: admin-service
  boot:
    admin:
      discovery:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      