import type { AnalysisResult, ResumeAnalysis } from "./types"

function severityLabel(severity: string): string {
  switch (severity) {
    case "critical":
      return "Critical"
    case "warning":
      return "Warning"
    default:
      return "Info"
  }
}

function qualityLabel(quality: string): string {
  switch (quality) {
    case "excellent":
      return "Excellent"
    case "good":
      return "Good"
    case "fair":
      return "Fair"
    default:
      return "Poor"
  }
}

export function scoreLabel(score: number): string {
  if (score >= 80) return "Excellent"
  if (score >= 60) return "Good"
  if (score >= 40) return "Fair"
  return "Needs Work"
}

export function buildReportMarkdown(result: AnalysisResult): string {
  const { analysis, fileName, wordCount, model, durationMs } = result
  const lines: string[] = []
  const section = (title: string) => lines.push("", `## ${title}`, "")

  lines.push(
    `# Resume Analysis Report`,
    ``,
    `- **File:** ${fileName}`,
    `- **Word count:** ${wordCount}`,
    `- **Model:** ${model}`,
    `- **Analysis time:** ${(durationMs / 1000).toFixed(1)}s`,
    `- **Generated:** ${new Date().toLocaleString()}`,
    ``,
    `# ATS Score: ${analysis.atsScore}/100 (${scoreLabel(analysis.atsScore)})`,
    ``,
    analysis.overallSummary
  )

  section("Score Breakdown")
  analysis.scoreBreakdown.forEach((c) => {
    lines.push(
      `- **${c.label}:** ${c.score}/100 (${Math.round(c.weight * 100)}% weight) - ${c.summary}`
    )
  })

  if (analysis.jobMatch) {
    section("Job Description Match")
    lines.push(`**Match: ${analysis.jobMatch.matchPercent}%**`)
    lines.push(analysis.jobMatch.note)
    if (analysis.jobMatch.strengths.length) {
      lines.push("", "**Strengths:**")
      analysis.jobMatch.strengths.forEach((s) => lines.push(`- ${s}`))
    }
    if (analysis.jobMatch.gaps.length) {
      lines.push("", "**Gaps:**")
      analysis.jobMatch.gaps.forEach((g) => lines.push(`- ${g}`))
    }
  }

  section("Keyword Analysis")
  if (analysis.keywordAnalysis.matched.length) {
    lines.push("**Found keywords:**")
    analysis.keywordAnalysis.matched.forEach((k) =>
      lines.push(`- ${k.keyword}${k.count > 1 ? ` (${k.count}x)` : ""}`)
    )
  }
  if (analysis.keywordAnalysis.missing.length) {
    lines.push("", "**Missing keywords:**")
    analysis.keywordAnalysis.missing.forEach((k) =>
      lines.push(`- ${k.keyword}`)
    )
  }

  section("Missing Skills")
  analysis.missingSkills.forEach((s) => lines.push(`- ${s}`))

  section("Skill Gaps")
  analysis.skillGaps.forEach((g) =>
    lines.push(`- **${g.skill}** (${g.priority} priority) - ${g.howToAcquire}`)
  )

  section("Formatting Issues")
  analysis.formattingIssues.forEach((f) =>
    lines.push(
      `- [${severityLabel(f.severity)}] **${f.issue}** - ${f.suggestion}`
    )
  )

  section("Grammar & Spelling")
  analysis.grammarIssues.forEach((g) =>
    lines.push(
      `- **Before:** ${g.original}`,
      `  **After:** ${g.correction}`,
      `  ${g.suggestion}`
    )
  )

  section("Recommended Actions")
  analysis.recommendations.forEach((r, i) => lines.push(`${i + 1}. ${r}`))

  section("Resume Summary Analysis")
  lines.push(
    `Quality: ${qualityLabel(analysis.summaryAnalysis.quality)} (${analysis.summaryAnalysis.score}/100)`
  )
  analysis.summaryAnalysis.feedback.forEach((f) => lines.push(`- ${f}`))

  section("Rewrites & Improvement Suggestions")
  analysis.rewriteSuggestions.forEach((r, i) => {
    lines.push(`### ${i + 1}. ${r.section}`)
    if (r.original) lines.push(`**Original:** ${r.original}`)
    if (r.suggested) lines.push(`**Suggested:** ${r.suggested}`)
    if (r.rationale) lines.push(`**Why:** ${r.rationale}`)
    lines.push("")
  })

  section("Cover Letter Suggestions")
  analysis.coverLetterSuggestions.forEach((s) => lines.push(`- ${s}`))

  section("Interview Preparation Tips")
  analysis.interviewTips.forEach((t) => {
    lines.push(`- **Q: ${t.question}**`)
    if (t.why) lines.push(`  Why asked: ${t.why}`)
    if (t.advice) lines.push(`  How to answer: ${t.advice}`)
  })

  lines.push(
    "",
    "---",
    "_Generated by Resume Analyzer. No resume data is stored - files and results are discarded after analysis._"
  )

  return lines.join("\n")
}

export function buildReportHtml(result: AnalysisResult): string {
  const escape = (text: string) =>
    text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  const markdown = buildReportMarkdown(result)
  const body = markdown
    .split("\n")
    .map((line) => {
      const trimmed = line.trim()
      if (trimmed.startsWith("## "))
        return `<h2>${escape(trimmed.slice(3))}</h2>`
      if (trimmed.startsWith("### "))
        return `<h3>${escape(trimmed.slice(4))}</h3>`
      if (trimmed.startsWith("# "))
        return `<h1>${escape(trimmed.slice(2))}</h1>`
      if (trimmed.startsWith("- "))
        return `<li>${escape(trimmed.slice(2))}</li>`
      if (/^\d+\.\s/.test(trimmed))
        return `<li>${escape(trimmed.replace(/^\d+\.\s/, ""))}</li>`
      if (trimmed === "---") return `<hr />`
      if (trimmed === "") return ""
      return `<p>${escape(trimmed)}</p>`
    })
    .join("\n")

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Resume Analysis Report - ${escape(result.fileName)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 24px; color: #1a1a1a; line-height: 1.6; }
  h1, h2 { border-bottom: 2px solid #eee; padding-bottom: 8px; }
  li { margin: 4px 0; }
  hr { border: none; border-top: 1px solid #eee; margin: 32px 0; }
</style>
</head>
<body>
${body}
</body>
</html>`
}

export function sanitizeFileName(fileName: string): string {
  const base = fileName.replace(/\.(pdf|docx)$/i, "")
  const cleaned = base
    .replace(/[^a-z0-9-_ ]/gi, "")
    .trim()
    .replace(/\s+/g, "-")
  return cleaned || "resume"
}

export function analyzeSummary(analysis: ResumeAnalysis) {
  return {
    label: scoreLabel(analysis.atsScore),
    color:
      analysis.atsScore >= 80
        ? "green"
        : analysis.atsScore >= 60
          ? "amber"
          : "red",
  }
}
